spring:
  datasource:
    url: jdbc:mysql://uiszmt9bxsrwllbf:eA1gVvTsT2cno0bz5cUf@bbcdlfupd8e6ro0pus3u-mysql.services.clever-cloud.com:3306/bbcdlfupd8e6ro0pus3u
    username: ${SERVER_USERNAME}
    password: ${SERVER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
