spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 44827517Tm#
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=root
#spring.datasource.password=44827517Tm#
#spring.datasource.hikari.maximum-pool-size=2
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# for debug purposes, coment latter
#spring.jpa.show-sql=true
